version: 2
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npx react-scripts build
      - persist_to_workspace:
          root: .
          paths:
            - build/*
  
  deploy:
    steps:
      - checkout- 
      - attach_workspace:
          at: build
  
  test:
    steps:
      - checkout
