version: 2
orbs:
  cypress: cypress-io/cypress@1.23.0
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npx react-scripts start
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
          
  test:
    working_directory: ~/test/cypress
    steps:
      - checkout
      - run: npx cypress run
