version: 2.1
orbs:
  node: circleci/node@12.18
  cypress: cypress-io/cypress@1
  newman: postman/newman@0.0.2
workflows:
  build_and_test:
    jobs:
      - build:
          steps:
            - checkout
            - run: react-scripts build
      - newman:
          executor: newman/postman-newman-docker
          steps:
            - checkout
            - run: echo "Start Newman tests"
            - newman/newman-run:
                - collection: collections/DevOps01.postman_collection.json
      - cypress:
          - cypress/run
